# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Requests/SendEncryptedSignatureRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Platform/Requests/SendEncryptedSignatureRequest.proto',
  package='POGOProtos.Networking.Platform.Requests',
  syntax='proto3',
  serialized_pb=_b('\nKPOGOProtos/Networking/Platform/Requests/SendEncryptedSignatureRequest.proto\x12\'POGOProtos.Networking.Platform.Requests\"<\n\x1dSendEncryptedSignatureRequest\x12\x1b\n\x13\x65ncrypted_signature\x18\x01 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENDENCRYPTEDSIGNATUREREQUEST = _descriptor.Descriptor(
  name='SendEncryptedSignatureRequest',
  full_name='POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypted_signature', full_name='POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest.encrypted_signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['SendEncryptedSignatureRequest'] = _SENDENCRYPTEDSIGNATUREREQUEST

SendEncryptedSignatureRequest = _reflection.GeneratedProtocolMessageType('SendEncryptedSignatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDENCRYPTEDSIGNATUREREQUEST,
  __module__ = 'POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest)
  ))
_sym_db.RegisterMessage(SendEncryptedSignatureRequest)


# @@protoc_insertion_point(module_scope)
