# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Capture/CaptureAward.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Enums import ActivityType_pb2 as POGOProtos_dot_Enums_dot_ActivityType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Data/Capture/CaptureAward.proto',
  package='POGOProtos.Data.Capture',
  syntax='proto3',
  serialized_pb=_b('\n*POGOProtos/Data/Capture/CaptureAward.proto\x12\x17POGOProtos.Data.Capture\x1a#POGOProtos/Enums/ActivityType.proto\"\x82\x01\n\x0c\x43\x61ptureAward\x12\x39\n\ractivity_type\x18\x01 \x03(\x0e\x32\x1e.POGOProtos.Enums.ActivityTypeB\x02\x10\x01\x12\x0e\n\x02xp\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05\x63\x61ndy\x18\x03 \x03(\x05\x42\x02\x10\x01\x12\x14\n\x08stardust\x18\x04 \x03(\x05\x42\x02\x10\x01\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Enums_dot_ActivityType__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAPTUREAWARD = _descriptor.Descriptor(
  name='CaptureAward',
  full_name='POGOProtos.Data.Capture.CaptureAward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='activity_type', full_name='POGOProtos.Data.Capture.CaptureAward.activity_type', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='xp', full_name='POGOProtos.Data.Capture.CaptureAward.xp', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='candy', full_name='POGOProtos.Data.Capture.CaptureAward.candy', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='stardust', full_name='POGOProtos.Data.Capture.CaptureAward.stardust', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=239,
)

_CAPTUREAWARD.fields_by_name['activity_type'].enum_type = POGOProtos_dot_Enums_dot_ActivityType__pb2._ACTIVITYTYPE
DESCRIPTOR.message_types_by_name['CaptureAward'] = _CAPTUREAWARD

CaptureAward = _reflection.GeneratedProtocolMessageType('CaptureAward', (_message.Message,), dict(
  DESCRIPTOR = _CAPTUREAWARD,
  __module__ = 'POGOProtos.Data.Capture.CaptureAward_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Data.Capture.CaptureAward)
  ))
_sym_db.RegisterMessage(CaptureAward)


_CAPTUREAWARD.fields_by_name['activity_type'].has_options = True
_CAPTUREAWARD.fields_by_name['activity_type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_CAPTUREAWARD.fields_by_name['xp'].has_options = True
_CAPTUREAWARD.fields_by_name['xp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_CAPTUREAWARD.fields_by_name['candy'].has_options = True
_CAPTUREAWARD.fields_by_name['candy']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_CAPTUREAWARD.fields_by_name['stardust'].has_options = True
_CAPTUREAWARD.fields_by_name['stardust']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
