# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/PokemonUpgradeSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Settings/Master/PokemonUpgradeSettings.proto',
  package='POGOProtos.Settings.Master',
  syntax='proto3',
  serialized_pb=_b('\n7POGOProtos/Settings/Master/PokemonUpgradeSettings.proto\x12\x1aPOGOProtos.Settings.Master\"\x84\x01\n\x16PokemonUpgradeSettings\x12\x1a\n\x12upgrades_per_level\x18\x01 \x01(\x05\x12#\n\x1b\x61llowed_levels_above_player\x18\x02 \x01(\x05\x12\x12\n\ncandy_cost\x18\x03 \x03(\x05\x12\x15\n\rstardust_cost\x18\x04 \x03(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POKEMONUPGRADESETTINGS = _descriptor.Descriptor(
  name='PokemonUpgradeSettings',
  full_name='POGOProtos.Settings.Master.PokemonUpgradeSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upgrades_per_level', full_name='POGOProtos.Settings.Master.PokemonUpgradeSettings.upgrades_per_level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='allowed_levels_above_player', full_name='POGOProtos.Settings.Master.PokemonUpgradeSettings.allowed_levels_above_player', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='candy_cost', full_name='POGOProtos.Settings.Master.PokemonUpgradeSettings.candy_cost', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stardust_cost', full_name='POGOProtos.Settings.Master.PokemonUpgradeSettings.stardust_cost', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['PokemonUpgradeSettings'] = _POKEMONUPGRADESETTINGS

PokemonUpgradeSettings = _reflection.GeneratedProtocolMessageType('PokemonUpgradeSettings', (_message.Message,), dict(
  DESCRIPTOR = _POKEMONUPGRADESETTINGS,
  __module__ = 'POGOProtos.Settings.Master.PokemonUpgradeSettings_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.PokemonUpgradeSettings)
  ))
_sym_db.RegisterMessage(PokemonUpgradeSettings)


# @@protoc_insertion_point(module_scope)
