# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/CollectDailyDefenderBonusMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Requests/Messages/CollectDailyDefenderBonusMessage.proto',
  package='POGOProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_pb=_b('\nNPOGOProtos/Networking/Requests/Messages/CollectDailyDefenderBonusMessage.proto\x12\'POGOProtos.Networking.Requests.Messages\"\"\n CollectDailyDefenderBonusMessageb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COLLECTDAILYDEFENDERBONUSMESSAGE = _descriptor.Descriptor(
  name='CollectDailyDefenderBonusMessage',
  full_name='POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['CollectDailyDefenderBonusMessage'] = _COLLECTDAILYDEFENDERBONUSMESSAGE

CollectDailyDefenderBonusMessage = _reflection.GeneratedProtocolMessageType('CollectDailyDefenderBonusMessage', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTDAILYDEFENDERBONUSMESSAGE,
  __module__ = 'POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Requests.Messages.CollectDailyDefenderBonusMessage)
  ))
_sym_db.RegisterMessage(CollectDailyDefenderBonusMessage)


# @@protoc_insertion_point(module_scope)
