# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/MapObjectsStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Map/MapObjectsStatus.proto',
  package='POGOProtos.Map',
  syntax='proto3',
  serialized_pb=_b('\n%POGOProtos/Map/MapObjectsStatus.proto\x12\x0ePOGOProtos.Map*E\n\x10MapObjectsStatus\x12\x10\n\x0cUNSET_STATUS\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x12\n\x0eLOCATION_UNSET\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MAPOBJECTSSTATUS = _descriptor.EnumDescriptor(
  name='MapObjectsStatus',
  full_name='POGOProtos.Map.MapObjectsStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET_STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCATION_UNSET', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=57,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_MAPOBJECTSSTATUS)

MapObjectsStatus = enum_type_wrapper.EnumTypeWrapper(_MAPOBJECTSSTATUS)
UNSET_STATUS = 0
SUCCESS = 1
LOCATION_UNSET = 2


DESCRIPTOR.enum_types_by_name['MapObjectsStatus'] = _MAPOBJECTSSTATUS


# @@protoc_insertion_point(module_scope)
