# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/FortSponsor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Map/Fort/FortSponsor.proto',
  package='POGOProtos.Map.Fort',
  syntax='proto3',
  serialized_pb=_b('\n%POGOProtos/Map/Fort/FortSponsor.proto\x12\x13POGOProtos.Map.Fort*B\n\x0b\x46ortSponsor\x12\x11\n\rUNSET_SPONSOR\x10\x00\x12\r\n\tMCDONALDS\x10\x01\x12\x11\n\rPOKEMON_STORE\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FORTSPONSOR = _descriptor.EnumDescriptor(
  name='FortSponsor',
  full_name='POGOProtos.Map.Fort.FortSponsor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET_SPONSOR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MCDONALDS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_STORE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=62,
  serialized_end=128,
)
_sym_db.RegisterEnumDescriptor(_FORTSPONSOR)

FortSponsor = enum_type_wrapper.EnumTypeWrapper(_FORTSPONSOR)
UNSET_SPONSOR = 0
MCDONALDS = 1
POKEMON_STORE = 2


DESCRIPTOR.enum_types_by_name['FortSponsor'] = _FORTSPONSOR


# @@protoc_insertion_point(module_scope)
