# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseItemXpBoostResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Inventory import AppliedItems_pb2 as POGOProtos_dot_Inventory_dot_AppliedItems__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Responses/UseItemXpBoostResponse.proto',
  package='POGOProtos.Networking.Responses',
  syntax='proto3',
  serialized_pb=_b('\n<POGOProtos/Networking/Responses/UseItemXpBoostResponse.proto\x12\x1fPOGOProtos.Networking.Responses\x1a\'POGOProtos/Inventory/AppliedItems.proto\"\xbe\x02\n\x16UseItemXpBoostResponse\x12N\n\x06result\x18\x01 \x01(\x0e\x32>.POGOProtos.Networking.Responses.UseItemXpBoostResponse.Result\x12\x39\n\rapplied_items\x18\x02 \x01(\x0b\x32\".POGOProtos.Inventory.AppliedItems\"\x98\x01\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x1b\n\x17\x45RROR_INVALID_ITEM_TYPE\x10\x02\x12!\n\x1d\x45RROR_XP_BOOST_ALREADY_ACTIVE\x10\x03\x12\x1c\n\x18\x45RROR_NO_ITEMS_REMAINING\x10\x04\x12\x18\n\x14\x45RROR_LOCATION_UNSET\x10\x05\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Inventory_dot_AppliedItems__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_USEITEMXPBOOSTRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='POGOProtos.Networking.Responses.UseItemXpBoostResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_ITEM_TYPE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_XP_BOOST_ALREADY_ACTIVE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_ITEMS_REMAINING', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_LOCATION_UNSET', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=305,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_USEITEMXPBOOSTRESPONSE_RESULT)


_USEITEMXPBOOSTRESPONSE = _descriptor.Descriptor(
  name='UseItemXpBoostResponse',
  full_name='POGOProtos.Networking.Responses.UseItemXpBoostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='POGOProtos.Networking.Responses.UseItemXpBoostResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applied_items', full_name='POGOProtos.Networking.Responses.UseItemXpBoostResponse.applied_items', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USEITEMXPBOOSTRESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=457,
)

_USEITEMXPBOOSTRESPONSE.fields_by_name['result'].enum_type = _USEITEMXPBOOSTRESPONSE_RESULT
_USEITEMXPBOOSTRESPONSE.fields_by_name['applied_items'].message_type = POGOProtos_dot_Inventory_dot_AppliedItems__pb2._APPLIEDITEMS
_USEITEMXPBOOSTRESPONSE_RESULT.containing_type = _USEITEMXPBOOSTRESPONSE
DESCRIPTOR.message_types_by_name['UseItemXpBoostResponse'] = _USEITEMXPBOOSTRESPONSE

UseItemXpBoostResponse = _reflection.GeneratedProtocolMessageType('UseItemXpBoostResponse', (_message.Message,), dict(
  DESCRIPTOR = _USEITEMXPBOOSTRESPONSE,
  __module__ = 'POGOProtos.Networking.Responses.UseItemXpBoostResponse_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.UseItemXpBoostResponse)
  ))
_sym_db.RegisterMessage(UseItemXpBoostResponse)


# @@protoc_insertion_point(module_scope)
