# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/VerifyChallengeResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Responses/VerifyChallengeResponse.proto',
  package='POGOProtos.Networking.Responses',
  syntax='proto3',
  serialized_pb=_b('\n=POGOProtos/Networking/Responses/VerifyChallengeResponse.proto\x12\x1fPOGOProtos.Networking.Responses\"*\n\x17VerifyChallengeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VERIFYCHALLENGERESPONSE = _descriptor.Descriptor(
  name='VerifyChallengeResponse',
  full_name='POGOProtos.Networking.Responses.VerifyChallengeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='POGOProtos.Networking.Responses.VerifyChallengeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['VerifyChallengeResponse'] = _VERIFYCHALLENGERESPONSE

VerifyChallengeResponse = _reflection.GeneratedProtocolMessageType('VerifyChallengeResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYCHALLENGERESPONSE,
  __module__ = 'POGOProtos.Networking.Responses.VerifyChallengeResponse_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.VerifyChallengeResponse)
  ))
_sym_db.RegisterMessage(VerifyChallengeResponse)


# @@protoc_insertion_point(module_scope)
