# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/AppliedItems.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Inventory import AppliedItem_pb2 as POGOProtos_dot_Inventory_dot_AppliedItem__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Inventory/AppliedItems.proto',
  package='POGOProtos.Inventory',
  syntax='proto3',
  serialized_pb=_b('\n\'POGOProtos/Inventory/AppliedItems.proto\x12\x14POGOProtos.Inventory\x1a&POGOProtos/Inventory/AppliedItem.proto\"?\n\x0c\x41ppliedItems\x12/\n\x04item\x18\x04 \x03(\x0b\x32!.POGOProtos.Inventory.AppliedItemb\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Inventory_dot_AppliedItem__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_APPLIEDITEMS = _descriptor.Descriptor(
  name='AppliedItems',
  full_name='POGOProtos.Inventory.AppliedItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='POGOProtos.Inventory.AppliedItems.item', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=168,
)

_APPLIEDITEMS.fields_by_name['item'].message_type = POGOProtos_dot_Inventory_dot_AppliedItem__pb2._APPLIEDITEM
DESCRIPTOR.message_types_by_name['AppliedItems'] = _APPLIEDITEMS

AppliedItems = _reflection.GeneratedProtocolMessageType('AppliedItems', (_message.Message,), dict(
  DESCRIPTOR = _APPLIEDITEMS,
  __module__ = 'POGOProtos.Inventory.AppliedItems_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Inventory.AppliedItems)
  ))
_sym_db.RegisterMessage(AppliedItems)


# @@protoc_insertion_point(module_scope)
