# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/Item/ItemId.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Inventory/Item/ItemId.proto',
  package='POGOProtos.Inventory.Item',
  syntax='proto3',
  serialized_pb=_b('\n&POGOProtos/Inventory/Item/ItemId.proto\x12\x19POGOProtos.Inventory.Item*\xc7\x05\n\x06ItemId\x12\x10\n\x0cITEM_UNKNOWN\x10\x00\x12\x12\n\x0eITEM_POKE_BALL\x10\x01\x12\x13\n\x0fITEM_GREAT_BALL\x10\x02\x12\x13\n\x0fITEM_ULTRA_BALL\x10\x03\x12\x14\n\x10ITEM_MASTER_BALL\x10\x04\x12\x0f\n\x0bITEM_POTION\x10\x65\x12\x15\n\x11ITEM_SUPER_POTION\x10\x66\x12\x15\n\x11ITEM_HYPER_POTION\x10g\x12\x13\n\x0fITEM_MAX_POTION\x10h\x12\x10\n\x0bITEM_REVIVE\x10\xc9\x01\x12\x14\n\x0fITEM_MAX_REVIVE\x10\xca\x01\x12\x13\n\x0eITEM_LUCKY_EGG\x10\xad\x02\x12\x1a\n\x15ITEM_INCENSE_ORDINARY\x10\x91\x03\x12\x17\n\x12ITEM_INCENSE_SPICY\x10\x92\x03\x12\x16\n\x11ITEM_INCENSE_COOL\x10\x93\x03\x12\x18\n\x13ITEM_INCENSE_FLORAL\x10\x94\x03\x12\x13\n\x0eITEM_TROY_DISK\x10\xf5\x03\x12\x12\n\rITEM_X_ATTACK\x10\xda\x04\x12\x13\n\x0eITEM_X_DEFENSE\x10\xdb\x04\x12\x13\n\x0eITEM_X_MIRACLE\x10\xdc\x04\x12\x14\n\x0fITEM_RAZZ_BERRY\x10\xbd\x05\x12\x14\n\x0fITEM_BLUK_BERRY\x10\xbe\x05\x12\x15\n\x10ITEM_NANAB_BERRY\x10\xbf\x05\x12\x15\n\x10ITEM_WEPAR_BERRY\x10\xc0\x05\x12\x15\n\x10ITEM_PINAP_BERRY\x10\xc1\x05\x12\x18\n\x13ITEM_SPECIAL_CAMERA\x10\xa1\x06\x12#\n\x1eITEM_INCUBATOR_BASIC_UNLIMITED\x10\x85\x07\x12\x19\n\x14ITEM_INCUBATOR_BASIC\x10\x86\x07\x12!\n\x1cITEM_POKEMON_STORAGE_UPGRADE\x10\xe9\x07\x12\x1e\n\x19ITEM_ITEM_STORAGE_UPGRADE\x10\xea\x07\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ITEMID = _descriptor.EnumDescriptor(
  name='ItemId',
  full_name='POGOProtos.Inventory.Item.ItemId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ITEM_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_POKE_BALL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_GREAT_BALL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_ULTRA_BALL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_MASTER_BALL', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_POTION', index=5, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_SUPER_POTION', index=6, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_HYPER_POTION', index=7, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_MAX_POTION', index=8, number=104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_REVIVE', index=9, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_MAX_REVIVE', index=10, number=202,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_LUCKY_EGG', index=11, number=301,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_INCENSE_ORDINARY', index=12, number=401,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_INCENSE_SPICY', index=13, number=402,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_INCENSE_COOL', index=14, number=403,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_INCENSE_FLORAL', index=15, number=404,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_TROY_DISK', index=16, number=501,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_X_ATTACK', index=17, number=602,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_X_DEFENSE', index=18, number=603,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_X_MIRACLE', index=19, number=604,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_RAZZ_BERRY', index=20, number=701,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_BLUK_BERRY', index=21, number=702,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_NANAB_BERRY', index=22, number=703,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_WEPAR_BERRY', index=23, number=704,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_PINAP_BERRY', index=24, number=705,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_SPECIAL_CAMERA', index=25, number=801,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_INCUBATOR_BASIC_UNLIMITED', index=26, number=901,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_INCUBATOR_BASIC', index=27, number=902,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_POKEMON_STORAGE_UPGRADE', index=28, number=1001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITEM_ITEM_STORAGE_UPGRADE', index=29, number=1002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=70,
  serialized_end=781,
)
_sym_db.RegisterEnumDescriptor(_ITEMID)

ItemId = enum_type_wrapper.EnumTypeWrapper(_ITEMID)
ITEM_UNKNOWN = 0
ITEM_POKE_BALL = 1
ITEM_GREAT_BALL = 2
ITEM_ULTRA_BALL = 3
ITEM_MASTER_BALL = 4
ITEM_POTION = 101
ITEM_SUPER_POTION = 102
ITEM_HYPER_POTION = 103
ITEM_MAX_POTION = 104
ITEM_REVIVE = 201
ITEM_MAX_REVIVE = 202
ITEM_LUCKY_EGG = 301
ITEM_INCENSE_ORDINARY = 401
ITEM_INCENSE_SPICY = 402
ITEM_INCENSE_COOL = 403
ITEM_INCENSE_FLORAL = 404
ITEM_TROY_DISK = 501
ITEM_X_ATTACK = 602
ITEM_X_DEFENSE = 603
ITEM_X_MIRACLE = 604
ITEM_RAZZ_BERRY = 701
ITEM_BLUK_BERRY = 702
ITEM_NANAB_BERRY = 703
ITEM_WEPAR_BERRY = 704
ITEM_PINAP_BERRY = 705
ITEM_SPECIAL_CAMERA = 801
ITEM_INCUBATOR_BASIC_UNLIMITED = 901
ITEM_INCUBATOR_BASIC = 902
ITEM_POKEMON_STORAGE_UPGRADE = 1001
ITEM_ITEM_STORAGE_UPGRADE = 1002


DESCRIPTOR.enum_types_by_name['ItemId'] = _ITEMID


# @@protoc_insertion_point(module_scope)
